controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - base_to_shoulder_joint
        - shoulder_to_upper_arm_joint
        - upper_arm_to_lower_arm_joint
        - lower_arm_to_wrist_joint
        - wrist_to_fixed_jaw_joint
        - fixed_to_moving_jaw_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
    use_sim_time: True